//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJobRequestSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobRequestDBEntities : DbContext
    {
        public JobRequestDBEntities()
            : base("name=JobRequestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblApprover> tblApprovers { get; set; }
        public virtual DbSet<tblAssessment> tblAssessments { get; set; }
        public virtual DbSet<tblAttachment> tblAttachments { get; set; }
        public virtual DbSet<tblEmailLog> tblEmailLogs { get; set; }
        public virtual DbSet<tblIncharge> tblIncharges { get; set; }
        public virtual DbSet<tblInchargePerson> tblInchargePersons { get; set; }
        public virtual DbSet<tblJigType> tblJigTypes { get; set; }
        public virtual DbSet<tblLeaderSubordinate> tblLeaderSubordinates { get; set; }
        public virtual DbSet<tblRequestType> tblRequestTypes { get; set; }
        public virtual DbSet<tblRequestType_Selected> tblRequestType_Selected { get; set; }
        public virtual DbSet<tblSignatory> tblSignatories { get; set; }
        public virtual DbSet<tblUniqueCode> tblUniqueCodes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblRequest> tblRequests { get; set; }
    
        public virtual int ChangePassword(Nullable<int> userid, string userpass)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var userpassParameter = userpass != null ?
                new ObjectParameter("userpass", userpass) :
                new ObjectParameter("userpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePassword", useridParameter, userpassParameter);
        }
    
        public virtual ObjectResult<string> GenerateJRFNo(string inchargeid)
        {
            var inchargeidParameter = inchargeid != null ?
                new ObjectParameter("inchargeid", inchargeid) :
                new ObjectParameter("inchargeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GenerateJRFNo", inchargeidParameter);
        }
    
        public virtual int GetApprover(string incharge_id)
        {
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetApprover", incharge_idParameter);
        }
    
        public virtual int GetApproverByEmpID(string empid, string incharge_id)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetApproverByEmpID", empidParameter, incharge_idParameter);
        }
    
        public virtual ObjectResult<GetAssessment_Result> GetAssessment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssessment_Result>("GetAssessment");
        }
    
        public virtual ObjectResult<GetDepartmentManager_Result> GetDepartmentManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentManager_Result>("GetDepartmentManager");
        }
    
        public virtual ObjectResult<GetDepartmentManagerByEmpID_Result> GetDepartmentManagerByEmpID(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentManagerByEmpID_Result>("GetDepartmentManagerByEmpID", empidParameter);
        }
    
        public virtual ObjectResult<GetDepartmentSupervisor_Result> GetDepartmentSupervisor(string code)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentSupervisor_Result>("GetDepartmentSupervisor", codeParameter);
        }
    
        public virtual ObjectResult<GetDepartmentSupervisorByEmpID_Result> GetDepartmentSupervisorByEmpID(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentSupervisorByEmpID_Result>("GetDepartmentSupervisorByEmpID", empidParameter);
        }
    
        public virtual ObjectResult<GetDepartmentSupervisorIncharge_Result> GetDepartmentSupervisorIncharge(string code, string incharge_id)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentSupervisorIncharge_Result>("GetDepartmentSupervisorIncharge", codeParameter, incharge_idParameter);
        }
    
        public virtual ObjectResult<GetDepartmentSupervisorInchargeByEmpID_Result> GetDepartmentSupervisorInchargeByEmpID(string empid, string incharge_id)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDepartmentSupervisorInchargeByEmpID_Result>("GetDepartmentSupervisorInchargeByEmpID", empidParameter, incharge_idParameter);
        }
    
        public virtual ObjectResult<GetIncharge_Result> GetIncharge()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIncharge_Result>("GetIncharge");
        }
    
        public virtual ObjectResult<GetInchargePerson_Result> GetInchargePerson(string inchargeid)
        {
            var inchargeidParameter = inchargeid != null ?
                new ObjectParameter("inchargeid", inchargeid) :
                new ObjectParameter("inchargeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInchargePerson_Result>("GetInchargePerson", inchargeidParameter);
        }
    
        public virtual ObjectResult<GetInchargePersonForCC_Result> GetInchargePersonForCC(string inchargeid)
        {
            var inchargeidParameter = inchargeid != null ?
                new ObjectParameter("inchargeid", inchargeid) :
                new ObjectParameter("inchargeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInchargePersonForCC_Result>("GetInchargePersonForCC", inchargeidParameter);
        }
    
        public virtual ObjectResult<GetIncomingRequests_Result> GetIncomingRequests(string inchargeid)
        {
            var inchargeidParameter = inchargeid != null ?
                new ObjectParameter("inchargeid", inchargeid) :
                new ObjectParameter("inchargeid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIncomingRequests_Result>("GetIncomingRequests", inchargeidParameter);
        }
    
        public virtual ObjectResult<string> GetJigType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetJigType");
        }
    
        public virtual int GetLeaderForCC(string incharge_id)
        {
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLeaderForCC", incharge_idParameter);
        }
    
        public virtual ObjectResult<GetRecordRequestType_Result> GetRecordRequestType(string jr_code)
        {
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecordRequestType_Result>("GetRecordRequestType", jr_codeParameter);
        }
    
        public virtual ObjectResult<GetRequest_Result> GetRequest(string uc)
        {
            var ucParameter = uc != null ?
                new ObjectParameter("uc", uc) :
                new ObjectParameter("uc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequest_Result>("GetRequest", ucParameter);
        }
    
        public virtual ObjectResult<GetRequestByIncharge_Result> GetRequestByIncharge(string incharge_id)
        {
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestByIncharge_Result>("GetRequestByIncharge", incharge_idParameter);
        }
    
        public virtual ObjectResult<string> GetRequestType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRequestType");
        }
    
        public virtual ObjectResult<GetUserByEmpID_Result> GetUserByEmpID(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserByEmpID_Result>("GetUserByEmpID", empidParameter);
        }
    
        public virtual ObjectResult<GetUserEmail_Result> GetUserEmail(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserEmail_Result>("GetUserEmail", empidParameter);
        }
    
        public virtual ObjectResult<GetUserRequests_Result> GetUserRequests(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserRequests_Result>("GetUserRequests", empidParameter);
        }
    
        public virtual ObjectResult<InchargeLogin_Result> InchargeLogin(string username, string userpass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpassParameter = userpass != null ?
                new ObjectParameter("userpass", userpass) :
                new ObjectParameter("userpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InchargeLogin_Result>("InchargeLogin", usernameParameter, userpassParameter);
        }
    
        public virtual int RejectRequest(string jr_code)
        {
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RejectRequest", jr_codeParameter);
        }
    
        public virtual int SaveRequest(string empid, string code, string sectCode, string incharge_id, string customer, string partname, string partcode, string jigtype, Nullable<double> quantity, Nullable<double> qtyprodperhr, Nullable<double> monthly_req, Nullable<double> machine_capacity, string problem_desc, string problem_image, string supportingdocs, string attachmentname, string attachmenttype, string jr_code)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var sectCodeParameter = sectCode != null ?
                new ObjectParameter("SectCode", sectCode) :
                new ObjectParameter("SectCode", typeof(string));
    
            var incharge_idParameter = incharge_id != null ?
                new ObjectParameter("incharge_id", incharge_id) :
                new ObjectParameter("incharge_id", typeof(string));
    
            var customerParameter = customer != null ?
                new ObjectParameter("customer", customer) :
                new ObjectParameter("customer", typeof(string));
    
            var partnameParameter = partname != null ?
                new ObjectParameter("partname", partname) :
                new ObjectParameter("partname", typeof(string));
    
            var partcodeParameter = partcode != null ?
                new ObjectParameter("partcode", partcode) :
                new ObjectParameter("partcode", typeof(string));
    
            var jigtypeParameter = jigtype != null ?
                new ObjectParameter("jigtype", jigtype) :
                new ObjectParameter("jigtype", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(double));
    
            var qtyprodperhrParameter = qtyprodperhr.HasValue ?
                new ObjectParameter("qtyprodperhr", qtyprodperhr) :
                new ObjectParameter("qtyprodperhr", typeof(double));
    
            var monthly_reqParameter = monthly_req.HasValue ?
                new ObjectParameter("monthly_req", monthly_req) :
                new ObjectParameter("monthly_req", typeof(double));
    
            var machine_capacityParameter = machine_capacity.HasValue ?
                new ObjectParameter("machine_capacity", machine_capacity) :
                new ObjectParameter("machine_capacity", typeof(double));
    
            var problem_descParameter = problem_desc != null ?
                new ObjectParameter("problem_desc", problem_desc) :
                new ObjectParameter("problem_desc", typeof(string));
    
            var problem_imageParameter = problem_image != null ?
                new ObjectParameter("problem_image", problem_image) :
                new ObjectParameter("problem_image", typeof(string));
    
            var supportingdocsParameter = supportingdocs != null ?
                new ObjectParameter("supportingdocs", supportingdocs) :
                new ObjectParameter("supportingdocs", typeof(string));
    
            var attachmentnameParameter = attachmentname != null ?
                new ObjectParameter("attachmentname", attachmentname) :
                new ObjectParameter("attachmentname", typeof(string));
    
            var attachmenttypeParameter = attachmenttype != null ?
                new ObjectParameter("attachmenttype", attachmenttype) :
                new ObjectParameter("attachmenttype", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveRequest", empidParameter, codeParameter, sectCodeParameter, incharge_idParameter, customerParameter, partnameParameter, partcodeParameter, jigtypeParameter, quantityParameter, qtyprodperhrParameter, monthly_reqParameter, machine_capacityParameter, problem_descParameter, problem_imageParameter, supportingdocsParameter, attachmentnameParameter, attachmenttypeParameter, jr_codeParameter);
        }
    
        public virtual int SaveSelectedRequestType(string request_type, string reqtype_details, string jr_code)
        {
            var request_typeParameter = request_type != null ?
                new ObjectParameter("request_type", request_type) :
                new ObjectParameter("request_type", typeof(string));
    
            var reqtype_detailsParameter = reqtype_details != null ?
                new ObjectParameter("reqtype_details", reqtype_details) :
                new ObjectParameter("reqtype_details", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSelectedRequestType", request_typeParameter, reqtype_detailsParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignature(string requestedby, string jr_code)
        {
            var requestedbyParameter = requestedby != null ?
                new ObjectParameter("requestedby", requestedby) :
                new ObjectParameter("requestedby", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignature", requestedbyParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureBothSVandManager(string appr_requestorleader, string appr_requestorleader_remarks, string appr_checker_manager, string appr_checker_manager_remarks, string jr_code)
        {
            var appr_requestorleaderParameter = appr_requestorleader != null ?
                new ObjectParameter("appr_requestorleader", appr_requestorleader) :
                new ObjectParameter("appr_requestorleader", typeof(string));
    
            var appr_requestorleader_remarksParameter = appr_requestorleader_remarks != null ?
                new ObjectParameter("appr_requestorleader_remarks", appr_requestorleader_remarks) :
                new ObjectParameter("appr_requestorleader_remarks", typeof(string));
    
            var appr_checker_managerParameter = appr_checker_manager != null ?
                new ObjectParameter("appr_checker_manager", appr_checker_manager) :
                new ObjectParameter("appr_checker_manager", typeof(string));
    
            var appr_checker_manager_remarksParameter = appr_checker_manager_remarks != null ?
                new ObjectParameter("appr_checker_manager_remarks", appr_checker_manager_remarks) :
                new ObjectParameter("appr_checker_manager_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureBothSVandManager", appr_requestorleaderParameter, appr_requestorleader_remarksParameter, appr_checker_managerParameter, appr_checker_manager_remarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForAssesstor(string assessedby, string assesstor_remarks, string jrfno, Nullable<bool> isjigexists, string assessmentcode, string assessmentremarks, string jr_code)
        {
            var assessedbyParameter = assessedby != null ?
                new ObjectParameter("assessedby", assessedby) :
                new ObjectParameter("assessedby", typeof(string));
    
            var assesstor_remarksParameter = assesstor_remarks != null ?
                new ObjectParameter("assesstor_remarks", assesstor_remarks) :
                new ObjectParameter("assesstor_remarks", typeof(string));
    
            var jrfnoParameter = jrfno != null ?
                new ObjectParameter("jrfno", jrfno) :
                new ObjectParameter("jrfno", typeof(string));
    
            var isjigexistsParameter = isjigexists.HasValue ?
                new ObjectParameter("isjigexists", isjigexists) :
                new ObjectParameter("isjigexists", typeof(bool));
    
            var assessmentcodeParameter = assessmentcode != null ?
                new ObjectParameter("assessmentcode", assessmentcode) :
                new ObjectParameter("assessmentcode", typeof(string));
    
            var assessmentremarksParameter = assessmentremarks != null ?
                new ObjectParameter("assessmentremarks", assessmentremarks) :
                new ObjectParameter("assessmentremarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForAssesstor", assessedbyParameter, assesstor_remarksParameter, jrfnoParameter, isjigexistsParameter, assessmentcodeParameter, assessmentremarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForAssesstorCannotProceed(string assessmentcode, string jr_code)
        {
            var assessmentcodeParameter = assessmentcode != null ?
                new ObjectParameter("assessmentcode", assessmentcode) :
                new ObjectParameter("assessmentcode", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForAssesstorCannotProceed", assessmentcodeParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForBothApprover(string appr_noter_sv, string appr_noter_sv_remarks, string appr_final_mng, string appr_final_mng_remarks, string jr_code)
        {
            var appr_noter_svParameter = appr_noter_sv != null ?
                new ObjectParameter("appr_noter_sv", appr_noter_sv) :
                new ObjectParameter("appr_noter_sv", typeof(string));
    
            var appr_noter_sv_remarksParameter = appr_noter_sv_remarks != null ?
                new ObjectParameter("appr_noter_sv_remarks", appr_noter_sv_remarks) :
                new ObjectParameter("appr_noter_sv_remarks", typeof(string));
    
            var appr_final_mngParameter = appr_final_mng != null ?
                new ObjectParameter("appr_final_mng", appr_final_mng) :
                new ObjectParameter("appr_final_mng", typeof(string));
    
            var appr_final_mng_remarksParameter = appr_final_mng_remarks != null ?
                new ObjectParameter("appr_final_mng_remarks", appr_final_mng_remarks) :
                new ObjectParameter("appr_final_mng_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForBothApprover", appr_noter_svParameter, appr_noter_sv_remarksParameter, appr_final_mngParameter, appr_final_mng_remarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForFinalAcceptance(string finalacceptanceby, string accept_remarks, string jr_code)
        {
            var finalacceptancebyParameter = finalacceptanceby != null ?
                new ObjectParameter("finalacceptanceby", finalacceptanceby) :
                new ObjectParameter("finalacceptanceby", typeof(string));
    
            var accept_remarksParameter = accept_remarks != null ?
                new ObjectParameter("accept_remarks", accept_remarks) :
                new ObjectParameter("accept_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForFinalAcceptance", finalacceptancebyParameter, accept_remarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForFirstApprover(string appr_noter_sv, string appr_noter_sv_remarks, string jr_code)
        {
            var appr_noter_svParameter = appr_noter_sv != null ?
                new ObjectParameter("appr_noter_sv", appr_noter_sv) :
                new ObjectParameter("appr_noter_sv", typeof(string));
    
            var appr_noter_sv_remarksParameter = appr_noter_sv_remarks != null ?
                new ObjectParameter("appr_noter_sv_remarks", appr_noter_sv_remarks) :
                new ObjectParameter("appr_noter_sv_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForFirstApprover", appr_noter_svParameter, appr_noter_sv_remarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForFirstChecker(string appr_checker_sv, string appr_checker_sv_remarks, string jr_code)
        {
            var appr_checker_svParameter = appr_checker_sv != null ?
                new ObjectParameter("appr_checker_sv", appr_checker_sv) :
                new ObjectParameter("appr_checker_sv", typeof(string));
    
            var appr_checker_sv_remarksParameter = appr_checker_sv_remarks != null ?
                new ObjectParameter("appr_checker_sv_remarks", appr_checker_sv_remarks) :
                new ObjectParameter("appr_checker_sv_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForFirstChecker", appr_checker_svParameter, appr_checker_sv_remarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForSecondApprover(string appr_final_mng, string appr_final_mng_remarks, string jr_code)
        {
            var appr_final_mngParameter = appr_final_mng != null ?
                new ObjectParameter("appr_final_mng", appr_final_mng) :
                new ObjectParameter("appr_final_mng", typeof(string));
    
            var appr_final_mng_remarksParameter = appr_final_mng_remarks != null ?
                new ObjectParameter("appr_final_mng_remarks", appr_final_mng_remarks) :
                new ObjectParameter("appr_final_mng_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForSecondApprover", appr_final_mngParameter, appr_final_mng_remarksParameter, jr_codeParameter);
        }
    
        public virtual int SaveSignatureForSecondChecker(string appr_checker_manager, string appr_checker_manager_remarks, string jr_code)
        {
            var appr_checker_managerParameter = appr_checker_manager != null ?
                new ObjectParameter("appr_checker_manager", appr_checker_manager) :
                new ObjectParameter("appr_checker_manager", typeof(string));
    
            var appr_checker_manager_remarksParameter = appr_checker_manager_remarks != null ?
                new ObjectParameter("appr_checker_manager_remarks", appr_checker_manager_remarks) :
                new ObjectParameter("appr_checker_manager_remarks", typeof(string));
    
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSignatureForSecondChecker", appr_checker_managerParameter, appr_checker_manager_remarksParameter, jr_codeParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateCompletion(string jr_code, Nullable<System.DateTime> completiondate, string jighistoryattachment, string jighistoryfilename, string jighistorycontenttype)
        {
            var jr_codeParameter = jr_code != null ?
                new ObjectParameter("jr_code", jr_code) :
                new ObjectParameter("jr_code", typeof(string));
    
            var completiondateParameter = completiondate.HasValue ?
                new ObjectParameter("completiondate", completiondate) :
                new ObjectParameter("completiondate", typeof(System.DateTime));
    
            var jighistoryattachmentParameter = jighistoryattachment != null ?
                new ObjectParameter("jighistoryattachment", jighistoryattachment) :
                new ObjectParameter("jighistoryattachment", typeof(string));
    
            var jighistoryfilenameParameter = jighistoryfilename != null ?
                new ObjectParameter("jighistoryfilename", jighistoryfilename) :
                new ObjectParameter("jighistoryfilename", typeof(string));
    
            var jighistorycontenttypeParameter = jighistorycontenttype != null ?
                new ObjectParameter("jighistorycontenttype", jighistorycontenttype) :
                new ObjectParameter("jighistorycontenttype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCompletion", jr_codeParameter, completiondateParameter, jighistoryattachmentParameter, jighistoryfilenameParameter, jighistorycontenttypeParameter);
        }
    
        public virtual ObjectResult<UserLogin_Result> UserLogin(string username, string userpass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpassParameter = userpass != null ?
                new ObjectParameter("userpass", userpass) :
                new ObjectParameter("userpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogin_Result>("UserLogin", usernameParameter, userpassParameter);
        }
    
        public virtual ObjectResult<GetManager_Result> GetManager(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManager_Result>("GetManager", empidParameter);
        }
    
        public virtual ObjectResult<GetSV_HeadBySubordinate_Result> GetSV_HeadBySubordinate(string empid)
        {
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSV_HeadBySubordinate_Result>("GetSV_HeadBySubordinate", empidParameter);
        }
    
        public virtual ObjectResult<GetManagerForIT_Result> GetManagerForIT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManagerForIT_Result>("GetManagerForIT");
        }
    
        public virtual ObjectResult<GetManagerForSafety_Result> GetManagerForSafety()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManagerForSafety_Result>("GetManagerForSafety");
        }
    
        public virtual ObjectResult<GetManagerForSmart_Result> GetManagerForSmart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetManagerForSmart_Result>("GetManagerForSmart");
        }
    
        public virtual ObjectResult<GetVicePresident_Result> GetVicePresident()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetVicePresident_Result>("GetVicePresident");
        }
    
        public virtual ObjectResult<Nullable<int>> VerifyIfEmployeeIsAvailable(string empID)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VerifyIfEmployeeIsAvailable", empIDParameter);
        }
    
        public virtual ObjectResult<GetAllApprovers_Result> GetAllApprovers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllApprovers_Result>("GetAllApprovers");
        }
    }
}
