//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJobRequestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachment
    {
        public int id { get; set; }
        public string attachmentfile { get; set; }
        public string contenttype { get; set; }
        public string attachmentname { get; set; }
        public string typeofattachment { get; set; }
        public Nullable<bool> issubmitted { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<bool> IsPrepared { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsCheckerReviewed { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsApproverReviewed { get; set; }
        public string jr_code { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    }
}
