//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJobRequestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailLog
    {
        public int LogID { get; set; }
        public string EmailUrl { get; set; }
        public string UserRole { get; set; }
        public string EmailAdd { get; set; }
        public string EmailFrom { get; set; }
        public string SentTo { get; set; }
        public string JR_Code { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
