//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJobRequestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInchargePerson
    {
        public string EmpID { get; set; }
        public string Incharge_ID { get; set; }
        public Nullable<bool> IsAssesstor { get; set; }
        public Nullable<bool> IsNoter { get; set; }
    }
}
