//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJobRequestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequest
    {
        public int ReqID { get; set; }
        public string EmpID { get; set; }
        public string JRF_No { get; set; }
        public Nullable<System.DateTime> JRF_Date { get; set; }
        public string DeptCode { get; set; }
        public string SectCode { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Incharge_ID { get; set; }
        public string Customer { get; set; }
        public string Partname { get; set; }
        public string Partcode { get; set; }
        public string JigType { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QtyProdPerHr { get; set; }
        public Nullable<double> Monthly_Req { get; set; }
        public Nullable<double> Machine_Capacity { get; set; }
        public Nullable<double> NextForeCast { get; set; }
        public string Problem_Desc { get; set; }
        public string AssessmentRemarks { get; set; }
        public string AssessmentCode { get; set; }
        public Nullable<bool> IsExistingJig { get; set; }
        public string JR_Code { get; set; }
        public string Req_Remarks { get; set; }
        public Nullable<bool> Is_Submitted { get; set; }
        public string Checker { get; set; }
        public string CheckerRemarks { get; set; }
        public Nullable<System.DateTime> DateChecked { get; set; }
        public Nullable<bool> Is_Checked { get; set; }
        public Nullable<bool> Is_Reviewed { get; set; }
        public string AssessedBy { get; set; }
        public string AssessedRemarks { get; set; }
        public Nullable<System.DateTime> DateAssessed { get; set; }
        public Nullable<bool> Is_Assessed { get; set; }
        public string Noter { get; set; }
        public string NoterRemarks { get; set; }
        public Nullable<System.DateTime> DateNoted { get; set; }
        public Nullable<bool> Is_Noted { get; set; }
        public string Manager { get; set; }
        public string ManagerRemarks { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<bool> Is_Approved { get; set; }
        public Nullable<bool> Is_JobAccepted { get; set; }
        public string AttachementStatus { get; set; }
        public Nullable<bool> Is_AttachmentApproved { get; set; }
        public string FinalAcceptanceBy { get; set; }
        public string AcceptRemarks { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public string Repairedby { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string RejectRemarks { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public string HoldBy { get; set; }
        public string HoldRemarks { get; set; }
        public string CompletionRemarks { get; set; }
        public Nullable<bool> IsSentToApprover_First { get; set; }
        public Nullable<bool> IsSentToApprover_Second { get; set; }
        public Nullable<System.DateTime> SecondSendDate { get; set; }
        public Nullable<bool> IsSentToApprover_Third { get; set; }
        public Nullable<System.DateTime> ThirdSendDate { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> SampleCounter { get; set; }
        public string RequestorsRemarks { get; set; }
    }
}
