//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJobRequestSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSignatory
    {
        public int signid { get; set; }
        public string RequestedBy { get; set; }
        public string Req_Remarks { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string Checker { get; set; }
        public string CheckerRemarks { get; set; }
        public Nullable<System.DateTime> DateChecked { get; set; }
        public string AssessedBy { get; set; }
        public string AssessedRemarks { get; set; }
        public Nullable<System.DateTime> DateAssessed { get; set; }
        public string Noter { get; set; }
        public string NoterRemarks { get; set; }
        public Nullable<System.DateTime> DateNoted { get; set; }
        public string Manager { get; set; }
        public string ManagerRemarks { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string FinalAcceptanceBy { get; set; }
        public string AcceptRemarks { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public string JR_Code { get; set; }
    }
}
